# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: pip
      directory: "/"
      cooldown:
          default-days: 7
      schedule:
          interval: daily
      groups: # One big pull request
          python-packages:
              patterns:
                  - "*"
    - package-ecosystem: "github-actions"
      # Workflow files stored in the default location of `.github/workflows`
      # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
      directory: "/"
      cooldown:
          default-days: 7
      schedule:
          interval: "weekly"
      groups:
          actions-packages:
              patterns:
                  - "*"
    - package-ecosystem: "npm"
      directory: "/.github/linters"
      cooldown:
          default-days: 7
      schedule:
          interval: "weekly"
      groups:
          actions-packages:
              patterns:
                  - "*"
