---
name: Manually Lint Code Base

on:
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          # Must be true to work
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false # I dont like this linter
          VALIDATE_PYTHON_BLACK: false # Just run it as black -l 120 .
          VALIDATE_PYTHON_ISORT: false # Just run manually 